thOptions2 = [
  {
    id: 1,
    name: "兽类",
    unit: "种",
    creator: 1,
    type: 2,
    createTime: "2020-09-22 10:23:36",
    pId: null,
    level: 1,
    creatorName: "超级管理员",
    filed: null,
    childs: [
      {
        id: 2,
        name: "果子狸",
        unit: "种",
        creator: 1,
        type: 2,
        createTime: "2020-09-22 10:23:57",
        pId: 1,
        level: 2,
        creatorName: "超级管理员",
        filed: null,
        childs: [
          {
            id: 3,
            name: "狸",
            unit: "种",
            creator: 1,
            type: 2,
            createTime: "2020-09-22 10:24:18",
            pId: 2,
            level: 3,
            creatorName: "超级管理员",
            filed: "1-1",
            childs: [],
          },
          {
            id: 8,
            name: "狐狸",
            unit: "种",
            creator: 1,
            type: 2,
            createTime: "2020-09-22 15:33:21",
            pId: 2,
            level: 3,
            creatorName: "超级管理员",
            filed: "1-2",
            childs: [],
          },
        ],
      },
    ],
  },
  {
    id: 4,
    name: "鱼类",
    unit: "种",
    creator: 1,
    type: 2,
    createTime: "2020-09-22 10:24:36",
    pId: null,
    level: 1,
    creatorName: "超级管理员",
    filed: "4-1",
    childs: [],
  },
];
thOptions1 = [
  {
    name: "森林碳汇",
    unit: "万亩",
    hasChildssss: true,
    level: 1,
    childs: [
      {
        name: "市局任务",
        unit: "万亩",
        level: 2,
        hasChildssss: false,
        childs: [],
        filed: "filed1",
      },
      {
        name: "实际完成",
        unit: "万亩",
        level: 2,

        hasChildssss: false,
        childs: [],
        filed: "filed2",
      },
      {
        name: "先造后补",
        unit: "万亩",
        level: 2,

        hasChildssss: false,
        childs: [],
        filed: "filed3",
      },
      {
        name: "碳汇造林",
        unit: "万亩",
        level: 2,

        hasChildssss: false,
        childs: [],
        filed: "filed4",
      },
    ],
  },
  {
    name: "生态景观林带建设",
    unit: "单位1",
    level: 1,
    hasChildssss: true,
    childs: [
      {
        name: "任务1",
        unit: "单位1",
        level: 2,
        hasChildssss: true,
        childs: [
          {
            name: "任务1",
            unit: "单位1",
            level: 3,
            hasChildssss: false,
            childs: [],
            filed: "filed5",
          },
        ],
      },
      {
        name: "任务2",
        unit: "单位1",
        level: 2,

        hasChildssss: false,
        childs: [],
        filed: "filed6",
      },
      {
        name: "任务3",
        unit: "单位1",
        level: 2,

        hasChildssss: false,
        childs: [],
        filed: "filed7",
      },
      {
        name: "任务4",
        unit: "单位1",
        level: 2,

        hasChildssss: false,
        childs: [],
        filed: "filed8",
      },
    ],
  },
  {
    name: "表头",
    unit: "单位3",
    hasChildssss: false,
    childs: [],
    filed: "filed9",
    level: 1,
  },
  {
    name: "森林抚育",
    unit: "单位2",
    hasChildssss: true,
    level: 1,
    childs: [
      {
        name: "省级森林抚育",
        unit: "单位2",
        level: 2,
        hasChildssss: false,
        childs: [],
        filed: "filed10",
      },
      {
        name: "中央财政森林抚育",
        unit: "单位2",
        hasChildssss: true,
        level: 2,
        childs: [
          {
            name: "2018年任务",
            unit: "单位2",
            hasChildssss: false,
            childs: [],
            filed: "filed11",
            level: 3,
          },
          {
            name: "2019年任务",
            unit: "单位2",
            hasChildssss: false,
            childs: [],
            filed: "filed12",
            level: 3,
          },
          {
            name: "2019年任务",
            unit: "单位2",
            hasChildssss: true,
            level: 3,
            childs: [
              {
                name: "2019年任务",
                unit: "单位2",
                hasChildssss: false,
                childs: [],
                filed: "filed13",
                level: 4,
              },
              {
                name: "2019年任务",
                unit: "单位2",
                level: 4,
                hasChildssss: true,
                childs: [
                  {
                    name: "2019年任务",
                    unit: "单位2",
                    level: 5,
                    hasChildssss: false,
                    childs: [],
                    filed: "filed14",
                  },
                  {
                    name: "2019年任务",
                    unit: "单位2",
                    level: 5,
                    hasChildssss: false,
                    childs: [],
                    filed: "filed15",
                  },
                  {
                    name: "2019年任务",
                    unit: "单位2",
                    level: 5,
                    hasChildssss: false,
                    childs: [],
                    filed: "filed16",
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
];
